# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages

script: 
- |
  R CMD build . --no-build-vignettes
  travis_wait 240 R CMD check --no--vignettes RSoptSC*tar.gz
  